# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: migreazy 2.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "migreazy"
  s.version = "2.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Francis Hwang"]
  s.date = "2014-06-29"
  s.description = "migreazy helps manage Rails migrations across git branches."
  s.email = "sera@fhwang.net"
  s.executables = ["migreazy"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "bin/migreazy",
    "lib/migreazy.rb",
    "migreazy.gemspec"
  ]
  s.homepage = "http://github.com/fhwang/migreazy"
  s.rubygems_version = "2.2.2"
  s.summary = "migreazy helps manage Rails migrations across git branches."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rugged>, ["~> 0.21.0"])
    else
      s.add_dependency(%q<rugged>, ["~> 0.21.0"])
    end
  else
    s.add_dependency(%q<rugged>, ["~> 0.21.0"])
  end
end

