# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{migreazy}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francis Hwang"]
  s.date = %q{2011-08-20}
  s.default_executable = %q{migreazy}
  s.description = %q{migreazy helps manage Rails migrations across git branches.}
  s.email = %q{sera@fhwang.net}
  s.executables = ["migreazy"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "bin/migreazy",
    "lib/migreazy.rb",
    "migreazy.gemspec"
  ]
  s.homepage = %q{http://github.com/fhwang/migreazy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{migreazy helps manage Rails migrations across git branches.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<grit>, [">= 0"])
    else
      s.add_dependency(%q<grit>, [">= 0"])
    end
  else
    s.add_dependency(%q<grit>, [">= 0"])
  end
end

